minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@vitest/eslint-plugin'
  - knip
  - '@kazupon/eslint-config'
  - '@kazupon/eslint-plugin'
  - jsr-exports-lint

onlyBuiltDependencies:
  - deno
  - esbuild
